### PR TITLE
Disconnect inactive user & multi-user fixes

### PR DESCRIPTION
**Pull request by pavtiger**

### CODE REVIEW

**Comment by pavtiger** [comment]
I invite @justdprroz to join the party and review this code. Feel free

**Comment by justdprroz** [comment]
1) I'm not really familiar with types of documents that you are working with, but probably it would be better to use example documents with less sensitive infomation

**Comment by justdprroz** [comment]
2) As non-debian based Linux user I would be happy to see some instruction that doesn'y rely on apt package manager

**Comment by justdprroz** [comment]
3) No clear instruction for running as web-server

**Comment by justdprroz** [comment]
4) **server.py:15** `from main import emit_console, process` - probably it is not good idea to import anything from main, I would rather place this functions to separated file

**Comment by justdprroz** [comment]
5) if use have separated web-server and cli program it would be better to have files with names such as `recognize_cli.py` or `recognize_ws.py` but you can name them differently

**Review by justdprroz — CHANGES_REQUESTED** [review]

**Comment by pavtiger** [comment]
> 1. I'm not really familiar with types of documents that you are working with, but probably it would be better to use example documents with less sensitive infomation

I mean this document is open in the internet so I should be able to use it, but still you are partially right

**Pull request merged**
